### ISSUE TITLE
Button "apply courses to requirements" does not do anything

### ISSUE THREAD

**Issue by seanbanko** [upenn/irs#1]
Following the "Student usage instructions" and reaching step 6, nothing happens when I click the blue "apply courses to requirements" button.

Browser: Firefox

**Comment by devietti** [comment]
That's unfortunate! Can you open up the JavaScript console and see if any messages have appeared there?

**Comment by seanbanko** [comment]
The console showed
```
Uncaught (in promise) Error: cannot parse courses
    getParser degree_requirements.ts:1828
    webMain degree_requirements.ts:2425
    onclick (index):1
```
I tried again making sure to ctrl-a to select the entire page on DegreeWorks (previously I had copy-pasted the entire contents of the"Courses Completed" popup, but not ctrl-a to get the entire page) and it seems to be working now. My mistake. Thank you.
