### ISSUE TITLE
Double counting 3 classes between MSE and BSE degrees

### ISSUE THREAD

**Issue by sisleyduanbr** [upenn/irs#5]
According to the accelerated master's website: "Students may double count up to three (3) graduate courses (four courses for Biotechnology) to fulfill both undergraduate and graduate degree requirements. This is subject to approval by both the undergraduate and graduate program chairs/directors." I don't think the system allows double counting right now.

**Comment by devietti** [comment]
It doesn't automatically place double-counts for you, but you should be able to drag-and-drop courses across degrees to double-count them.

**Comment by devietti** [comment]
I'll go ahead and close this for now, but if you are seeing any weird behavior with the double-counts please re-open or create a new issue.
