### ISSUE TITLE
Some foreign language courses do not count as SSH

### ISSUE THREAD

**Issue by ezhao02** [upenn/irs#8]
I've tried a couple Chinese courses (CHIN), Japanese courses (JPAN), and Korean courses (KORN), and none of these seem to be counted, even though https://ugrad.seas.upenn.edu/student-handbook/courses-requirements/social-sciences-and-humanities-breadth/ says that all foreign language courses count as humanities. Perhaps this is due to the website only listing the EALC department and not also the CHIN courses for languages? If so, this issue might exist for the NELC department as well (which includes ARAB, HEBR, TURK, and PERS courses).

**Comment by devietti** [comment]
Thanks! Added these in bda94ff1d170a0a
